### PR TITLE
ManyLinux Binary Support

### PR DESCRIPTION
**Pull request by spencer-hanson**
I've built file for linux using the manylinux docker image provided by python's manylinux project (https://github.com/pypa/manylinux) And added them to the build script.

I also modified magic.py to find the .so files on linux with virtual environments, since binary discovery is different on linux distributions.

In setup.py, I bumped the version number from 0.4.13 to 0.4.14, Updated the author list and emails, and  added the linux object files to package_data.

### CODE REVIEW

**Review by julian-r — CHANGES_REQUESTED** [review]
Cool! Ok I just want to state that usually a Linux distribution has file support, i see that this is especially interesting for docker images. In line https://github.com/julian-r/python-magic/pull/2/files#diff-94c8e55ec0189c4c696c1bdd866df13eR181 you would exclude the already installed libraries support, i think.

**Comment by spencer-hanson** [comment]
Alright. Couldn't they just install `python-magic` and not `python-magic-bin` if they already have binaries installed they would like to use?

Otherwise I can add a check to use native libraries first, and have this be a fallback.

**Comment by spencer-hanson** [comment]
bump

**Comment by spencer-hanson** [comment]
bump

**Comment by julian-r** [comment]
I am now looking in howto maintain this fork, I'd actually prefer to keep it somehow close to the original project and already asked the maintainer about it.

Let's see:
 https://github.com/ahupp/python-magic/issues/137

If not i will setup a build pipline here, would you take care of the future linux bin releases?

**Pull request merged**
